name: app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
<<<<<<< HEAD
  http: ^1.4.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
=======


  http: ^1.4.0
  flutter:

    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.1.0


>>>>>>> be622d1 (Updated project)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
<<<<<<< HEAD
  uses-material-design: true

  assets:
    - assets/icons/
=======
  assets:
    - assets/animations/
  uses-material-design: true


>>>>>>> be622d1 (Updated project)
